---
- hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli

- name: FETCH MACHINES FROM NETBOX
  run_once: true
  delegate_to: localhost
  uri:
    url: "http://netbox.sqrd.lab/api/dcim/platforms/1"
    method: GET
  register: sites