---
- name: Install Docker
  hosts: "{{ hostname }}"
  vars_files:
   - SQRD.yml  

  tasks:
  - name: upgrade all packages using dnf
    dnf:
      name: "*"
      state: latest
    become: yes      
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest    

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes

  - name: Install the latest version of Docker Engine and containerd
    dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    notify: Start and enable docker

  - name: install pip
    shell:
      yum install python3-pip -y

  - name: Download and install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-x86_64
      dest: /usr/bin/docker-compose
      mode: 0755

  handlers:
    - name: Start and enable docker
      systemd:
        name: docker
        state: started
        enabled: yes    

