---
- name: Intro to Ansible Playbooks
  hosts: all

  tasks:
    - name: check OS version
      debug: var=ansible_os_family

    - block:     # for redhat
 
  tasks:
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:

        when: ansible_os_family == "RedHat"      