---
- name: update hosts
  hosts: all

  tasks:
  - name: upgrade all packages using dnf
    dnf:
      name: "*"
      state: latest
    become: yes      
    when: ansible_facts['os_family'] == "RedHat"

  tasks:
  - name: upgrade all packages using apt
    apt:
      name: "*"
      state: latest
    become: yes      
    when: ansible_facts['os_family'] == "Debian"